<?php

########################################################################
# Extension Manager/Repository config file for ext: "ns_ext_compatibility"
#
# Auto generated by Extension Builder 2018-04-13
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TYPO3 Extensions Compatibility Report',
	'description' => 'One of the only TYPO3 extension which provides all the features like TYPO3 Extensions Compatibility Report, Notification of new update via Email, System overview report, Compatible with all major version of TYPO3 from 4.x to 8.x. This extension will help you to check TYPO3 upgrade feasibility and complexity to analyze upgrade estimation and define a perfect upgrade workflow.',
	'category' => 'module',
	'author' => 'Sanjay Chauhan [NITSAN Technologies]',
	'author_email' => 'sanjay@nitsan.in',
	'author_company' => 'NITSAN Technologies',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.1.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.5.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
